name: Terraform Module Test

concurrency:
  group: "${{ github.ref }}/terraform_test"
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - ".github/workflows/pal.yml"

permissions:
  contents: write
  packages: read
  id-token: write
  issues: write # read/write to repo issues
  statuses: write
  pull-requests: write

jobs:
  call-terrraform:
    permissions:
      contents: write
      packages: read
      id-token: write
      issues: write # read/write to repo issues
      statuses: write
      pull-requests: write
    uses: "smc-workflow/terraform-workflows/.github/workflows/terraform-module-test.yml@v4"
    with:
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      GITHUB_APP_ID: ${{ vars.TF_GITHUB_APP_ID }}
      GITHUB_APP_INSTALLATION_ID: ${{ vars.TF_GITHUB_APP_INSTALLATION_ID }}
      GITHUB_OWNER: ${{ vars.TF_GITHUB_OWNER }}
      CONTAINER_IMAGE: "ghcr.io/smc-devcontainer/azure-terraform/devcon:0.1.1"
    secrets:
      TF_GITHUB_APP_PEM_FILE: ${{ secrets.TF_GITHUB_APP_PEM_FILE }}
      CONTAINER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}