name: Terraform Module Test

concurrency:
  group: "${{ github.ref }}/terraform_test"
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - ".github/workflows/pal.yml"

permissions:
  contents: write
  packages: read
  id-token: write
  issues: write # read/write to repo issues
  statuses: write
  pull-requests: write

jobs:
  call-terrraform:
    permissions:
      contents: write
      packages: read
      id-token: write
      issues: write # read/write to repo issues
      statuses: write
      pull-requests: write
    uses: "smc-workflow/terraform-workflows/.github/workflows/terraform-module-test.yml@v4"
    with:
      CONTAINER_IMAGE: "ghcr.io/smc-devcontainer/azure-terraform/devcon:0.1.1"
    secrets: inherit
